using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Exception_finally
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int n1 = 4;
            int n2 = 2;
            int res = 0;
            try              //error will come here and program terminates
            {
                res = n1 / n2;
            }
            catch(Exception ee)  // code will execute only if run time error occurs
            {
                Console.WriteLine("Catch Block is Executing");
                Console.WriteLine(ee.ToString());
            }
            finally //code will execute whehter error occurs or not
            {
                Console.WriteLine("finally block is executing");
                Console.WriteLine("res="+res);
            }
            Console.WriteLine("bye");
        }
    }
}
